version: "3.7"

services:
  biapi-dev:
    container_name: biapi
    image: biapi
    build:
      context: .
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    depends_on:
      - bidb
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - API_INTERNAL_PORT=8081
      - API_INTERNAL_TEST_PORT=8082
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - JWT_DOMAIN=localhost
      - DB_SERVER=dbserver:5432
      - DB_NAME=bidb
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - ADMIN_ORCID=${ADMIN_ORCID}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_ACTOR=${GITHUB_ACTOR}
    ports:
      - 8081:8081
    networks:
      - backend
  bidb:
    image: postgis/postgis:12-3.0
    container_name: bidb
    environment:
      - POSTGRES_DB=bidb
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - biapi_data
    networks:
      backend:
        aliases:
          - dbserver

networks:
  backend:

volumes:
  biapi_data:
    name: biapi_data
