version: "3.7"

services:
  biapi-dev:
    container_name: biapi
    image: biapi
    build:
      context: .
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    depends_on:
      - bidb
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - API_INTERNAL_PORT=${API_INTERNAL_PORT}
      - API_INTERNAL_TEST_PORT=${API_INTERNAL_TEST_PORT}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - JWT_DOMAIN=${JWT_DOMAIN}
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - ADMIN_ORCID=${ADMIN_ORCID}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_ACTOR=${GITHUB_ACTOR}
    ports:
      - ${API_INTERNAL_PORT}:${API_INTERNAL_PORT}
    networks:
      - backend
  bidb:
    image: postgres:11.4
    container_name: bidb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - biapi_data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - dbserver

networks:
  backend:

volumes:
  biapi_data:
    name: biapi_data
