version: "3.7"

services:
  biapi-dev:
    container_name: biapi
    build:
      context: .
    depends_on:
      - bidb
    volumes:
      - type: bind
        source: ./src
        target: /biapi/src/
    environment:
      - API_INTERNAL_PORT=8081
      - OAUTH_CLIENT_ID='APP-ZX6M8LSAN3YIIAQ5'
      - JWT_DOMAIN='localhost'
      - DB_SERVER='dbserver:5432'
      - DB_NAME='bidb'
      - DB_USERNAME='postgres'
  ports:
      - 8081:8081
    networks:
      - backend
  bidb:
    image: postgres:11.4
    environment:
      POSTGRES_DB: 'bidb'
      POSTGRES_PASSWORD: 'postgres'
    container_name: bidb
    ports:
      - 5432:5432
    volumes:
      - biapi_data
    networks:
      backend:
        aliases:
          - dbserver

networks:
  backend:

volumes:
  biapi_data:
    name: biapi_data