version: "3.7"

services:
  biapi-dev:
    container_name: biapi
    image: biapi
    build:
      context: .
      args:
        HOST_USER_ID: ${USER_ID:-0}
        HOST_GROUP_ID: ${GROUP_ID:-0}
    depends_on:
      - bidb
    volumes:
      - type: bind
        source: ./src
        target: /biapi/src/
    environment:
      - API_INTERNAL_PORT=8081
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - JWT_DOMAIN=localhost
      - DB_SERVER=dbserver:5432
      - DB_NAME=bidb
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    ports:
      - 8081:8081
    networks:
      - backend
  bidb:
    image: postgres:11.4
    environment:
      - POSTGRES_DB=bidb
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: bidb
    ports:
      - 5432:5432
    volumes:
      - biapi_data
    networks:
      backend:
        aliases:
          - dbserver
  bitestdb:
    image: postgres:11.4
    environment:
      - POSTGRES_DB=bitest
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: bitest
    ports:
      - 8765:5432
    networks:
      backend:
        aliases:
          - testserver

networks:
  backend:

volumes:
  biapi_data:
    name: biapi_data