oauth:
  clientId: ${OAUTH_CLIENT_ID}
  clientSecret: ${OAUTH_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  cookie:
    domain: ${JWT_DOMAIN:localhost}


server:
  port: ${API_INTERNAL_PORT:8081}

db:
  default:
    host: ${DB_SERVER:`localhost:5432`}
    name: ${DB_NAME:bidb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}