micronaut:
  application:
    name: bi-api
    instance:
      id: ${random.shortuuid}
  server:
    port: 8081
    cors:
      enabled: true
  security:
    enabled: true
    oauth2:
      enabled: true
      callback-uri: /sso/success{/provider}
      login-uri: /sso/start{/provider}
      default-provider: orcid
      clients:
        orcid:
          client-id: '${oauth.clientId}'
          client-secret: '${oauth.clientSecret}'
          scopes:
            - openid
            - /authenticate
          authorization:
            url: ${oauth.authUrl:`https://sandbox.orcid.org/oauth/authorize`}
          token:
              url: ${oauth.tokenUrl:`https://sandbox.orcid.org/oauth/token`}
              auth-method: client-secret-post
          openid:
            issuer: ${oauth.openId.Issuer:`https://sandbox.orcid.org`}
            jwks-uri: ${oauth.openId.jwksUri:`https://sandbox.orcid.org/oauth/jwks`}
            user-info:
              url: ${oauth.openId.userInfoUrl:`https://sandbox.orcid.org/oauth/userinfo`}
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
          cookie-name: phylo-token
          cookie-secure: ${jwt.cookie.secure:true}
          http-only: true
          cookie-domain: ${jwt.cookie.domain:localhost}
          login-success-target-url: ${micronaut.server.host:localhost}:${micronaut.server.port:8080}/sso/success
          login-failure-target-url: ${micronaut.server.host:localhost}:${micronaut.server.port:8080}/unauthorized
        bearer:
          enabled: false
        signatures:
          secret:
            generator:
              secret: ${jwt.secret}
              jws-algorithm: HS256

#datasources:
#  default:
#    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
#    username: ${db.username}
#    password: ${db.password}
#    driverClassName: 'org.postgresql.Driver'
#
#api:
#  oauth:
#    user-search:
#      orcid:
#        url: ${oauth.user-search-url:`https://pub.sandbox.orcid.org/v2.1/search`}
#
web:
  url: ${webUrl:`http://localhost:3000`}