oauth:
  clientId: ${OAUTH_CLIENT_ID}
  clientSecret: ${OAUTH_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${API_INTERNAL_PORT:8081}

adminOrcid: ${ADMIN_ORCID}

datasources:
  default:
    url: jdbc:postgresql://${DB_SERVER:`localhost:5432`}/${DB_NAME:bidb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}