micronaut:
  application:
    name: bi-api
    instance:
      id: ${random.shortuuid}
  server:
    port: 8081
    cors:
      enabled: true
  bi:
    api:
      version: v1
  security:
    enabled: true
    oauth2:
      enabled: true
      callback-uri: /sso/success{/provider}
      login-uri: /sso/start{/provider}
      default-provider: orcid
      clients:
        orcid:
          client-id: '${oauth.clientId}'
          client-secret: '${oauth.clientSecret}'
          scopes:
            - openid
            - /authenticate
          authorization:
            url: ${oauth.authUrl:`https://sandbox.orcid.org/oauth/authorize`}
          token:
              url: ${oauth.tokenUrl:`https://sandbox.orcid.org/oauth/token`}
              auth-method: client-secret-post
          openid:
            issuer: ${oauth.openId.Issuer:`https://sandbox.orcid.org`}
            jwks-uri: ${oauth.openId.jwksUri:`https://sandbox.orcid.org/oauth/jwks`}
            user-info:
              url: ${oauth.openId.userInfoUrl:`https://sandbox.orcid.org/oauth/userinfo`}
    token:
      jwt:
        enabled: true
        cookie:
          enabled: true
          cookie-name: phylo-token
          cookie-secure: ${jwt.cookie.secure:true}
          http-only: true
          cookie-domain: ${jwt.cookie.domain:localhost}
          login-success-target-url: ${web.login.url}
          login-failure-target-url: ${web.login.url}
          logout-target-url: ${web.logout.url}
        bearer:
          enabled: false
        signatures:
          secret:
            generator:
              secret: ${jwt.secret}
              jws-algorithm: HS256
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
        get-allowed: true
        path: /logout
jackson:
  date-format: yyyy-MM-dd'T'HH:mm:ssZ
flyway:
  datasources:
    default:
      locations: classpath:db.migration
      enabled: true
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'
    

#datasources:
#  default:
#    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
#    username: ${db.username}
#    password: ${db.password}
#    driverClassName: 'org.postgresql.Driver'
#
#api:
#  oauth:
#    user-search:
#      orcid:
#        url: ${oauth.user-search-url:`https://pub.sandbox.orcid.org/v2.1/search`}
#
web:
  login:
    url: ${web.loginUrl:`http://localhost:8080?new-login=true`}
  logout:
    url: ${web.logoutUrl:`http://localhost:8080`}