oauth:
  clientId: <production client id>
  clientSecret: <production client secret>

jwt:
  secret: <production jwt secret>
  cookie:
    secure: true
    domain: <production domain>

#Change this if the production port needs to be different than 8080
#server:
#  port: 8080

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/bidb
    username: <db username>
    password: <db password>