Hello <user_name>,

Welcome to Breeding Insight!

Before using your account, you need will need to associate your OrcID account to your BI account. If you do not have an OrcID account already, please sign up for one before activating your BI account.

Follow the link below to activate your account:

<new_signup_link>

This link will expire in <expiration_time>. Please do not reply to this email.

