#
#    See the NOTICE file distributed with this work for additional information
#    regarding copyright ownership.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

server.port = 8080
server.servlet.context-path=/brapi/v2

spring.datasource.url=jdbc:postgresql://${BRAPI_DB_SERVER}/${BRAPI_DB}
spring.datasource.hikari.data-source-properties.stringtype=unspecified
spring.datasource.username=${BRAPI_DB_USER}
spring.datasource.password=${BRAPI_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# This property when set to true makes it so that a DB transaction is open through the body of a request, nullifying the use of @Transactional.
# It is generally recommended that this be set to false, and methods are properly annotated and release the transactions when complete.
# However, many of the endpoints already rely on this kind of connection infrastructure and changing is more trouble than it's worth.
spring.jpa.open-in-view=true

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.hibernate.ddl-auto=validate

# Use these to help debug queries.
# The stats will tell you how long hibernate transactions are taking, how many queries occur, how many entities are being flushed/accessed, etc.
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.generate_statistics=false

spring.flyway.locations=classpath:db/migration,classpath:db/sql,classpath:org/brapi/test/BrAPITestServer/db/migration
spring.flyway.schemas=public
spring.flyway.baselineOnMigrate=true

spring.mvc.dispatch-options-request=true

security.oidc_discovery_url=https://example.com/auth/.well-known/openid-configuration
security.enabled=false
security.issuer_url=http://example.com/issuerurl

# This should either be set in accordance with a maximum number of SQL parameters (on JOIN FETCHES of collections,
# if there is more than one collection the IDs of each entity need to be passed through as parameters, and there is a SQL
# maximum of 65535.  See GermplasmService.findGermplasmEntities()),
# whatever returns in a reasonable amount of time,
# or if you want to limit for the sake of server efficiency.
paging.page-size.max-allowed=65000

paging.page-size.default=1000
