/*
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

create table breeding_method (
                                  like base_entity INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES,
                                  name TEXT,
                                  abbreviation TEXT,
                                  description TEXT,
                                  category TEXT,
                                  genetic_diversity TEXT
);

insert into breeding_method
(abbreviation, name, description, genetic_diversity, category)
VALUES
( 'CCT', 'Collected (cultivated)', 'Collected germplasm represents a sample collected from in situ ag or market conditions', 'Maintenance (0)', 'Acquisition' ),
( 'WLD', 'Collected (wild)', 'Germplasm collected from wild conditions', 'Maintenance (0)', 'Acquisition' ),
( 'LDR', 'Collected (landrace)', 'Domesticated, locally adapted, traditional germplasm', 'Maintenance (0)', 'Acquisition' ),
( 'CFT', 'Clone formation (TC)', 'Clone propagated via tissue culture', 'Maintenance (0)', 'Asexual' ),
( 'CFV', 'Clone formation (Veg)', 'Clone propagated via the normal vegetative material', 'Maintenance (0)', 'Asexual' ),
( 'SOC', 'Somoclone', 'Variation induced through tissue culture ', 'Generative (+)', 'Asexual' ),
( 'LTS', 'Storage long term', 'Longterm germplasm storage. Genetic drift is expected. Storage is about -180C.', 'Generative (+)', 'Asexual' ),
( 'MTS', 'Storage medium term', 'Medium term germplasm storage. Some genetic drift is expected. Storage is between 0-40C and low RH.', 'Generative (+)', 'Asexual' ),
( 'BCR', 'Backcross', 'Offspring formed by crossing a hybrid with one of its parents or parent population', 'Derivative (-)', 'Cross' ),
( 'BBT', 'Broad based test', 'Test (Top) cross between a known plant or population and a broad based (many plants) tester. For practical reasons the tester population is used as the male which can be stored pollen.', 'Generative (+)', 'Cross' ),
( 'CCX', 'Complex cross', 'Cross between two three-way or more complex crosses ', 'Generative (+)', 'Cross' ),
( 'CVC', 'Convergent cross', 'Series of single crosses, each cross then combined into double crosses, each of these then crossed etc. ', 'Generative (+)', 'Cross' ),
( 'MCT', 'Male complex top cross', 'Cross between a male inbred line and a three-way or more complex cross among inbred lines, thus the female is segregating for genotypes as well as gametes.', 'Generative (+)', 'Cross' ),
( 'HYB', 'Hybrid formation', 'Germplasm generated by crossing inbred lines', 'Generative (+)', 'Cross' ),
( 'CCU', 'Cross, cytoplasm unknown', 'Cross with unknown female parent', 'Generative (+)', 'Cross' ),
( 'DCX', 'Double cross', 'Cross between two single crosses ', 'Generative (+)', 'Cross' ),
( 'FTC', 'Female complex top cross', 'Cross between a female inbred line and a three-way or more complex cross among inbred lines, thus the male is segregating for genotypes as well as gametes.', 'Generative (+)', 'Cross' ),
( 'NBT', 'Narrow based test', 'Test (Top) cross between a known plant or population and a narrow based (1 or few plants) population. For practical reasons the tester population or line is used as the male which can be stored pollen.', 'Generative (+)', 'Cross' ),
( 'RMG', 'Random male gamete cross', 'A random bulk of pollen/semen from some population used to pollinate/fertilize female. Male is a population and will be recorded as a single entity.', 'Generative (+)', 'Cross' ),
( 'MGB', 'Male gamete bulk cross', 'Pollen/semen bulk from known males is used to pollinate/fertilize, multiple male parents are recorded in pedigree', 'Generative (+)', 'Cross' ),
( 'BPC', 'Biparental cross', 'Cross between two individuals', 'Generative (+)', 'Cross' ),
( 'SYN', 'Synthetic formation', 'Bulk germplasm derived from crossing in all combinations, a number of lines that combine well with each other.  Once synthesized, a synthetic is maintained by open-fertilization in isolation.', 'Maintenance (0)', 'Cross' ),
( 'TCR', 'Test cross', 'Crosses made for generating hybrids for early generation testing. The females can be lines in any generation of inbreeding or DH lines, and the male is usually a fixed inbred line, or a F1 single cross between two fixed inbred lines.', 'Generative (+)', 'Cross' ),
( 'C3W', 'Three-way cross', 'Cross between two individual or populations, one inbred and the other heterozygous (usually an F1) ', 'Generative (+)', 'Cross' ),
( 'SSD', 'Single seed descent', 'Derived through the production of a single individual without selection from each individual in a segregating population.', 'Derivative (-)', 'Selection' ),
( 'HDB', 'Seed increase half diallel cross bulk', 'Seed bulk generated from a half diallel cross. Each parent mated to all others, no selfs, no reciprocals, usually not in isolation and all seed bulked. Here the aim is to maintain a population, not recombine a set of selected families.', 'Maintenance (0)', 'Cross' ),
( 'IMT', 'Induced mutation', 'Germplasm generated by application of mutagen', 'Generative (+)', 'GM' ),
( 'TRC', 'Transgenic cytoplasm', 'Individual derived from genetic transformation of a cytoplasm inclusion (e.g. chloroplast) in a self fertilizing species.', 'Generative (+)', 'GM' ),
( 'TRN', 'Transgenic nucleus', 'Individual derived from genetic transformation of the nucleus.', 'Generative (+)', 'GM' ),
( 'CRS', 'CRISPR', 'Germplasm created via CRISPR editing', 'Generative (+)', 'GM' ),
( 'BSD', 'Breeders seed', '"Pure" seed produced by breeder for breeder', 'Maintenance (0)', 'Increase' ),
( 'BPP', 'Bulk or population ', 'Bulk individual or population of germplasm', 'Maintenance (0)', 'Increase' ),
( 'CDD', 'Certified seed', '"Pure" seed produced under supervision by government protocols.', 'Maintenance (0)', 'Increase' ),
( 'CVR', 'Cultivar release', 'Offspring will be released as a cultivar', 'Maintenance (0)', 'Increase' ),
( 'FSD', 'Foundation seed', '"Pure" seed derived from Breeders seed (usually kept by seed producing organization).', 'Maintenance (0)', 'Increase' ),
( 'INC', 'Increase', 'Increase offsping/seed of an individual germplasm or population', 'Maintenance (0)', 'Increase' ),
( 'FDB', 'Seed increase full diallel cross bulk', 'Seed bulk generated from a full diallel cross. Each parent mated to all others, including all reciprocals but not selfs, usually not in isolation and all seed bulked. Aim is to maintain a population, not recombine a set of selected families.', 'Maintenance (0)', 'Increase' ),
( 'PDB', 'Seed increase partial diallel cross bulked', 'Seed bulk generated from a partial diallel cross. Each parent mated to some, but not all other parents in a pattern, no selfs. Aim is to maintain a population, not recombine a set of selected families.', 'Maintenance (0)', 'Increase' ),
( 'MSC', 'Increase subset cross', 'Parents divided into sets and bulked male gametes from each set used to fertilize other sets, usually not in isolation. Self fertilization avoided, all offspring bulked. Here the aim is to maintain a population, not recombine a set of selected families.', 'Maintenance (0)', 'Increase' ),
( 'OFN', 'Offspring numbering', 'Numbering single indivuduals from a population without generation advance', 'Maintenance (0)', 'Inventory' ),
( 'OFT', 'Open fertilization', 'Open pollination/fertilization of female germplasm', 'Generative (+)', 'OP' ),
( 'POC', 'Polycross', 'Progeny produced by fertilization with random male gametes, usually by open-mating in isolation among the selected lines. Creation of half-sib families', 'Generative (+)', 'OP' ),
( 'ALP', 'Allopolyploid', 'Polyploid formed by doubling the chromosomes of a cross between two or more species.', 'Generative (+)', 'Ploidy' ),
( 'AUT', 'Autopolyploid', 'Polyploid formed by doubling the chromosome number within a species.', 'Generative (+)', 'Ploidy' ),
( 'ANE', 'Aneupolyploid', 'Polyploid having a chromosome number that is not an exact multiple of the haploid number, usually additive', 'Generative (+)', 'Ploidy' ),
( 'DHL', 'Double haploid', 'Individual produced by doubling a haploid individual', 'Derivative (-)', 'Ploidy' ),
( 'HAP', 'Haploid', 'Individual with chromosome content of reduced gamete. ', 'Derivative (-)', 'Ploidy' ),
( 'TTT', 'Testosterone treatment', 'Neomale generated from female via testosterone treatment, which results in genotypic females that are phenotypically male.', 'Maintenance (0)', 'Selection' ),
( 'RJY', 'Royal Jelly', 'Diploid female induced to become a queen (capable of sexual reproduction)', 'Maintenance (0)', 'Selection' ),
( 'FMS', 'Full mass selection', 'Production of next generation by selecting before fertilization/pollination, selecting on both male and female sides.', 'Derivative (-)', 'Selection' ),
( 'HMS', 'Half mass selection', 'Production of next generation by selecting after fertlization/pollination; selection on female side only.', 'Derivative (-)', 'Selection' ),
( 'NMT', 'Natural mutation', 'A recognized naturally occurring mutation ', 'Generative (+)', 'Selection' ),
( 'UNK', 'Unknown ', 'Unknown increase method for recording acquisitions or historical pedigrees', 'Maintenance (0)', 'Unknown' ),
( 'UGM', 'Unknown generative method', 'Unknown generative method for recording acquisitions or historical pedigrees', 'Generative (+)', 'Unknown' ),
( 'UBM', 'Unknown derivative method', 'Germplasm produced by an undefined derivative methods for recording acquisitions or historical pedigrees', 'Derivative (-)', 'Unknown' ),
( 'UMM', 'Unknown maintenance method', 'Germplasm produced by an undefined maintenance methods for recording acquisitions or historical pedigrees', 'Maintenance (0)', 'Unknown' ),
( 'RBK', 'Random bulk', 'Bulked germplasm produced by random mating or selection', 'Derivative (-)', 'Selection' ),
( 'RSL', 'Restorer selection', 'Restorer Lines selected at the end of a program to backcross a gene which restores male fertility to lines carrying a Male Sterile Cytoplasm (CMS).', 'Derivative (-)', 'Selection' ),
( 'ROG', 'Roguing', 'Germplasm selected for elimination.  Also known as culling.', 'Derivative (-)', 'Selection' ),
( 'SBK', 'Selected bulk', 'Bulked germplasm from selections', 'Derivative (-)', 'Selection' ),
( 'SLF', 'Self and bulk', 'Selfing a single plant or population and bulk seed', 'Derivative (-)', 'Selection' ),
( 'SIS', 'Single individual selection', 'Derivation through selection of a single individual, inflorescence, fruit or seed from a population', 'Derivative (-)', 'Selection' );
