name: maven build

on:
  pull_request:
    type: [opened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bidb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 13

      - name: Build with Maven
        run: mvn -B flyway:migrate install --file pom.xml --settings settings.xml 
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_SERVER: localhost
          DB_NAME: bidb
          GITHUB_ACTOR: $GITHUB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_INTERNAL_TEST_PORT: 8081
